import type { Metadata } from "next";
import { inter, playfairDisplay, workSans } from "./fonts";
import "./globals.css";
import { Header, Footer } from "@/components/common";

export const metadata: Metadata = {
  title: "Injuro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${playfairDisplay.className} ${workSans.className} antialiased`}
      >
        <Header />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
